# Generated by Django 3.1.7 on 2021-03-20 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="users",
            field=models.ManyToManyField(
                related_name="communities", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
